[workspace]
members = [
  "crates/db",
  "crates/http-server",
  "crates/smtp-server"
  # Reusable Libraries 
]

resolver  = "3"


[workspace.dependencies]
axum = "0.7"
tokio = { version = "1", features = ["full"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["cors"] }

# Database
sqlx = { version = "0.7", features = ["runtime-tokio-native-tls", "postgres", "uuid", "chrono", "json"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Email Processing
mail-parser = "0.9"

# Utilities
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
dotenv = "0.15"
rand = "0.8"
reqwest = { version = "0.12", features = ["json"] }
thiserror = "1.0"


